# Generated by Django 3.2.18 on 2023-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230816_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='under_warranty',
            field=models.BooleanField(null=True),
        ),
    ]
