# Generated by Django 3.2.18 on 2023-08-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_diagnosticreport_ready_for_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticreport',
            name='unsuccessfully_processing',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
