# Generated by Django 3.2.18 on 2023-05-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diagnosticsrequest_ready_for_repair'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
                ('diagnostic_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.diagnosticsrequest')),
            ],
        ),
    ]
