# Generated by Django 3.2.18 on 2023-08-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_diagnosticreport_unsuccessfully_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreport',
            name='unsuccessfully_processing',
            field=models.BooleanField(default=False),
        ),
    ]
