# Generated by Django 3.2.18 on 2023-05-24 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticreport',
            name='price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pricing'),
        ),
    ]
