# Generated by Django 3.2.18 on 2023-09-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_diagnosticreport_unsuccessfully_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsrequest',
            name='state',
            field=models.CharField(choices=[('PROCESSED', 'Processed'), ('PROCESSING', 'Processing'), ('UNPROCESSED', 'Unprocessed')], default=1, max_length=11),
            preserve_default=False,
        ),
    ]
