# Generated by Django 3.2.18 on 2023-09-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_diagnosticsrequest_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelwarrant',
            name='state',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('UNAPPROVED', 'Unapproved')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
