# Generated by Django 3.2.18 on 2023-05-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_diagnosticreport_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='schedule_appointment',
        ),
    ]
