# Generated by Django 3.2.18 on 2023-09-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_travelwarrant_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelwarrant',
            name='data',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
