# Generated by Django 3.2.18 on 2023-09-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_travelwarrant_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelwarrant',
            name='data',
        ),
    ]
