# Generated by Django 3.2.18 on 2023-09-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_travelwarrant_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticsrequest',
            name='state',
            field=models.CharField(choices=[('PROCESSED', 'Processed'), ('PROCESSING', 'Processing'), ('INITIAL', 'Initial'), ('UNPROCESSED', 'Unprocessed')], max_length=11),
        ),
    ]
