# Generated by Django 3.2.18 on 2023-09-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_diagnosticsrequest_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleshooting',
            name='state',
            field=models.CharField(choices=[('PROCESSED', 'Processed'), ('PROCESSING', 'Processing'), ('INITIAL', 'Initial'), ('UNPROCESSED', 'Unprocessed')], default=1, max_length=11),
            preserve_default=False,
        ),
    ]
